### ISSUE TITLE
Include germline variants

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1147]
Get the list of variants without any annotation, (germline variants should be pathology actionable), across all genes, from the internal MSK study

Use the excel from the pathology department

- [ ] Curate the same variant differently?
- [ ] Or just a flag and add a different description for germline?
- [ ] Get the data from portal about the pathology dignoistic

**Comment by zhx828** [comment]
we need this.
