### ISSUE TITLE
1.0.0 release checklist

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1537]
- [x] change &nbsp; to space
- [x] test review mode and gene page when 2 curators work on the same gene
- [x] Convert the data to new drug structure
- [x] Make sure all fields mentioned in https://github.com/oncokb/oncokb/issues/1340 will be deleted
- [x] Make sure https://github.com/oncokb/oncokb/issues/1441 is checked
