### ISSUE TITLE
oncokb-core Refactoring TODO list

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1615]
- [ ] The input query should not be updated. A clone should be done and the input should be purified(trim ...)
- [ ] Spring Boot
- [ ] Utils should be done in services
- [ ] Need to differentiate the get/find. Find would not create a new entity if does not exist. Alteration for instance, the get will create a new alteration based on protein change and be annotated if the script cannot find a mapped alteration in the database.

**Comment by zhx828** [comment]
We need this
