### ISSUE TITLE
TODO items about blocking propagation between solid tumors and liquid tumors

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1658]
- [x] ~~The current Other Tumor Type summary applies to all tumors. If we decide to put a block, we should figure out a way to curate Other Solid Tumor Type and Other Liquid Tumor Type~~ (the curation team looked at the data, and decided to keep the Other Tumor Type summary not moved and apply to all tumors)
- [x] Allow select different propagation for solid and heme
- [x] Introduce Other Solid Tumors, Other Liquid Tumors
- [x] Remove Pediatric Tumors
