### ISSUE TITLE
Checklist:  Change to legacy.oncokb.org Other services using oncokb

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1780]
- [x] GN - no usage
- [x] cBioPortal - public https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/35
- [x] oncokb-annotator
- [x] react mutation mapper
