### ISSUE TITLE
Checklist: Add documents for instances that using legacy.oncokb.org

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1784]
- [ ] GN - do not use oncokb
- [ ] cBioPortal - public https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/35
- [ ] oncokb-annotator (https://github.com/oncokb/oncokb-annotator/pull/33)
- [ ] react mutation mapper (https://github.com/cBioPortal/react-mutation-mapper/pull/115/files)
- [ ] DMP annotation
