### ISSUE TITLE
Token expiration email: To production checklist

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2075]
- [x] 14 days email sent 
- [x] token is renewed if the link is clicked
- [x] 3 days email sent
- [x] token is renewed if the link is clicked
- [x] token is not renewed if the link is not clicked
- [x] The user will be given an error message in the login page if the token is expired
- [x] Check the annotator is not working any more with the old token
- [x] User registration still works
