### ISSUE TITLE
Fully delete user account

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2098]
We have requests to fully delete a user account.

- [x] jhi_user /  jhi_user_authority

- [x] token / token_stats

- [x] user_details

- [x] user_mails

- [x] do not delete audits, but add a deletion record to audit
