### ISSUE TITLE
Evaluate reCAPTCHA for client protection

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2099]
- https://developers.google.com/recaptcha/intro
- https://www.baeldung.com/spring-security-registration-captcha 
- https://medium.com/codeep-io/how-to-use-google-recaptcha-with-react-38a5cd535e0d

- [ ] reCAPTCHA should be used to protect certain API calls.

- [ ] Once reCAPTCHA is enabled, public_website role probably will no longer needed.

Steps after discussion on 10/19 with JJ and Aaron:

- [x] Implement recaptcha for frontend only

- [x] figure out whether google requires to show the privacy icon

- [x] if it does, we need to work with Legal team to see whether that's ok with them

- [x] have a webdriver/PhantomJS script ready to prevent browser crawler

**Comment by Leowisd** [comment]
Potential way to hide reCAPTCHA badge:
https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed
![image](https://user-images.githubusercontent.com/32425638/96610087-db779480-12c0-11eb-9472-3eaa4a804593.png)
