### ISSUE TITLE
GRCh38 Checks before deploying to production

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2207]
- [x] All public endpoints support reference genome 
- [x] Reference genome description is up to date
- [x] The latest oncokb-core tests are passing
