### ISSUE TITLE
Create Cancer hotspot for GRCh38

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2270]
- [ ] Pick the GRCh38 transcripts for hotspot list, this should be the ones very similar to 37. For any transcript that is not the exactly same of 37, we should use uniport default.

- [ ] Find out the difference between hotspot transcript, GN canonical and oncokb transcript 

- [ ] Provide the script to GN for sequence alignment

- [ ] Generate GRCh38 cancer hotspot list

- [ ] Add to oncokb

- [ ] Add to GN

- [ ] Check oncokb script to use appropriate cancer hotspot list for different reference genome

**Comment by zhx828** [comment]
We are not making the cancer hotspot list for GRCh38 but wait for the new manual script to be published based on a bigger dataset.
