### ISSUE TITLE
Refactoring curation platform

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2385]
Technology list
- [ ] Mobx 6
- [ ] Latest React/React Hooks

Priority list
- [ ] Firebase authentication
- [ ] Set up the website, dev.curate.oncokb.org/gene/MECOM
- [ ] Find the react lib to work with firebase, two-way data binding
- [ ] Routing, default to a gene page
- [ ] Focus on Gene page(Summary, Background)
- [ ] Review mode
