### ISSUE TITLE
Retire legacy oncokb.org instance

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2588]
The old instance has caused a lot of confusions from our users. We should remove it from the root and set up a new route for the legacy instance.

- [x] Forward oncokb.org to www.oncokb.org
- [x] Give instructions on how to change the oncokb url to v1 in cbioportal
- [x] Update the API document about the new change

**Comment by zhx828** [comment]
Reached out to the UHN group to update the oncokb link.
JJ is ok to use legacy.oncokb.org instead of v1.oncokb.org

**Comment by zhx828** [comment]
UHN updated the internal portal. We can retire legacy now.
