### ISSUE TITLE
Cache queries in Redis

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2589]
We have reached to a point that caching api requests may be a way to improve the performance. We have made some efforts in https://github.com/oncokb/oncokb/pull/2498 to cache the same query in POST methods. But we need to do that on global level.

- [x] Make sure the cache is gzipped, yup, this is a lesson learned from cbioportal team
- [x] Make sure to distinguish the priority of cache. Eventually the cache will reach to the threshold that we have to get rid of some of them. The caches indicated with high priority should stay in the cache stack as much as possible
- [x] Cache gene list
- [x] Cache info endpoint

**Comment by zhx828** [comment]
We are using a custom redis cache manager from portal team which comes with a gzip functionality. Luke mentioned the gzip can be further improved.
