### ISSUE TITLE
Store and monitor specific data usage

### ISSUE THREAD

**Issue by benzuzu** [oncokb/oncokb#2635]
We want to monitor data usage to ensure users are not spamming or misusing the website.

- [x] Store token_stats in a txt file or specialized database to reduce storage consumption.
- [x] Get a grasp of a reasonable number of IP addresses to be used per account and set a limit based on that amount
- [ ] ~Identify a place to store specific gene query parameters for all API calls (in a txt file, as a new column, etc.)~
- [ ] ~Analyze this stored data to see if users' usage is "meaningful" or just spam~
- [ ] Send suspicious users to a channel in slack where they can be dealt with manually
