### ISSUE TITLE
Monthly data usage cap

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2698]
First step
- [x] the cap is set to 10k for monthly usage
- [x] Update the token usage on a daily basis
- [x] send email to dev team when an user uses more than 10k
- [x] send email to dev team for all users who have exceeded this monthly threshold in the past (on hold)

~Second step~
- [ ] ~send email to user when the usage exceeds the threshold, the email should be sent on a monthly basis.~
- [ ] ~the email should only send to the academic users.~
