### ISSUE TITLE
Deploy company feature in production

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2791]
- [x] Release oncokb-public 3.5.8 which includes disable-registration (Hongxin)
- [x] Merge  the add-company to master and release 3.6.0-alpha.0 (Hongxin)
- [x] Release 3.5.8 (Hongxin)
- [x] Generate a new database schema locally (Calvin)
- [x] Dump the data from oncokb-public production DB without create/deletion schemes. (Calvin)
- [x] Import the data from above to the new database schema (Calvin)
- [ ] ~Upload the data to AWS Aurora. (Calvin)~
- [x] Update oncokb-public-beta to use 3.6.0 and use the appropriate configmap for DB connection. (Hongxin)
- [x] Release oncokb-public using 3.6.0 (Calvin)
