### ISSUE TITLE
Rename oncokb-meta to oncokb-java-commons

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3265]
We are going to develop oncokb-frontend-commons to include the packages that can be shared across projects in the frontend. To align the naming and avoid the confusion, we are going to name the oncokb-meta to oncokb-java-commons.

- [ ] Rename to oncokb-java-commons
- [ ] Remind Calvin to delete the fork
- [ ] Tag the release to 0.0.1
- [ ] Add action to build jitpack upon release
- [ ] Update the dependency of oncokb-public and oncokb-curation(oncokb-transcript)
