### ISSUE TITLE
Generate all transcript, ensemble genes and gene fragments

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3294]
We currently generate only when adding a new gene to curation platform to avoid necessary data. But since we want to share the oncokb-transcript dataset with clients, we probably should generate all ~40K genes in the database.

```[tasklist]
### Tasks
- [x] Add Transcript_Flag table to list all relevant flags (MSKIMPACT, MANE etc.) Similar to ensembl transcript table https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000157764;r=7:140719327-140924929
- [x] Import all MSKIMPACT 505 gene transcript in GRCh37
- [x] Import all MANE Select in GRCh38
- [x] Import all MANE Clinical Plus in GRCh38
```

**Comment by zhx828** [comment]
For GRCh38, we should generate MANE transcripts first.
