### ISSUE TITLE
Test when alteration in both VUS and mutation lists

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3450]
When alteration is in both lists, the VUS should not overwrite any evidence.

```[tasklist]
### Tasks
- [x] In the validation tool, we should warn admin when an alteration is in both mutation list and VUS list
- [x] In the API response, if the same alteration is in mutation list and VUS list, we should not mark vus as true
- [x] VUS evidence should be excluded when matching. Especially the lastEdit timestamp should not be used
```
