### ISSUE TITLE
Allow curator to add mutation summary in curation platform

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3479]
Similar to tumor type summary, if a mutation summary is manually entered, it will trump the autogenerated summary.

```[tasklist]
### Tasks
- [x] Add textarea with title Mutation Summary above the Mutation Effect collapsible https://github.com/oncokb/oncokb-transcript/pull/433
- [x] Parse mutation summary when saving to core https://github.com/oncokb/oncokb/pull/3786
- [ ] https://github.com/oncokb/oncokb/issues/3794
```
