### ISSUE TITLE
Fix small issues with oncokb-curation

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3485]
```[tasklist]
### Tasks
- [x] Make Firebase optional during development
- [x] Don't use Redis for spring session during development.
- [x] Curation panel dropdown values are not cleared when navigation to another PMA to curate
-  [x] Fix some cancer types not showing up in dropdown. Support maintype, subtype and code.
```
