### ISSUE TITLE
Update HGVSg/GC pages breadcrumb

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3487]
Currently, we show gene/alteration after annotating HGVSg or GenomicChange. But ideally we should show the o

```[tasklist]
### Tasks
- [x] Show original query with reference genome. e.g. `GRCh37 / 5:g.112151184A>G`
- [x] Allow user to change reference genome
- [x] Allow user to change query
```
