### ISSUE TITLE
Add option to delete company

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3617]
Similar to delete account, we could add the Danger Zone to delete a company.
![Screenshot 2023-11-29 at 1 30 29 PM](https://github.com/oncokb/oncokb/assets/5400599/4fb4a17a-e1d3-46b8-aaac-1b47874a28f9)

```[tasklist]
### Tasks
- [x] Add Danger Zone in company page with confirm modal
- [x] Delete company info from DB completely
- [x] Deassociate users with the company if there are
- [x] If the company has a commercial license, we should deactivate all associated users
- [x] Discussion: can we archive the company? What do we need to do to achieve that
```
