### ISSUE TITLE
Allow curator to add a new gene

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3639]
We want to enable curator to add a new gene for curation. The current https://curation.oncokb.org/curation page lists all existing genes. After adding a panel on the right, under the Tools, we could add an option to add a new gene. The new gene should be selected from https://curation.oncokb.org/gene. We have a GeneSelect to use.

```[tasklist]
### Tasks
- [x] Add a tool `Curate new gene`, under the title, include a gene dropdown and create button
- [x] If the gene already exists, add a warning message, and the create button is disabled
- [x] After creating the gene, the curator will be redirected to the gene page
```
