### ISSUE TITLE
Update Year End Review page

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3647]
```[tasklist]
### Tasks
- [x] Add left panel in the news page, Year End Review section and Data Release section
- [x] Move the year end review to news page
- [x] Add 2023 year end review
```
