### ISSUE TITLE
Adjust curation page styles and address feedback

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3674]
```[tasklist]
### Tasks
- [x] Add `background-color: #f1f9ff` to text inputs
- [ ] https://github.com/oncokb/oncokb/issues/3679
- [x] Allow user to click on collapsible to expand/collapse instead of just clicking on button
- [x] Color code the VUS by recency of update ((red = last updated >6 months, yellow = last updated 3 > 6 months, etc)
- [x] Vertically center align labels with dropdowns
- [x] Move therapy collapsible above Dx/Px collapsibles
- [x] Remove R3 option from filtering
- [x] Change 'no' option to 'None' in mutation filter
- [ ] https://github.com/oncokb/oncokb/issues/3678
- [ ] https://github.com/oncokb/oncokb/issues/3677
- [ ] https://github.com/oncokb/oncokb/issues/3676
- [ ] https://github.com/oncokb/oncokb/issues/3680
- [ ] https://github.com/oncokb/oncokb/issues/3687
- [ ] https://github.com/oncokb/oncokb/issues/3705
- [ ] https://github.com/oncokb/oncokb/issues/3689
- [ ] https://github.com/oncokb/oncokb/issues/3690
- [ ] https://github.com/oncokb/oncokb/issues/3692
- [ ] https://github.com/oncokb/oncokb/issues/3693
- [ ] https://github.com/oncokb/oncokb/issues/3675
```
```[tasklist]
### Continued...
- [ ] https://github.com/oncokb/oncokb/issues/3694
- [ ] https://github.com/oncokb/oncokb/issues/3691
- [ ] https://github.com/oncokb/oncokb/issues/3699
- [ ] https://github.com/oncokb/oncokb/issues/3698
- [ ] https://github.com/oncokb/oncokb/issues/3700
- [ ] https://github.com/oncokb/oncokb/issues/3701
- [ ] https://github.com/oncokb/oncokb/issues/3702
```
