### ISSUE TITLE
Add options to all therapy section dropdowns

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3680]
```[tasklist]
### Tasks
- [x] Look into how to color code resistance vs sensitivity
- [x] Add LOE definitions to LOE dropdown options
- [x] ~Capitalize 'FDA' in FDA level dropdown~
- [x] Add Diagnostic levels
- [x] Add prognostic levels
- [x] Add therapy level of evidences with propagation logic
```

**Comment by calvinlu3** [comment]
Fixed in https://github.com/oncokb/oncokb-transcript/pull/221
