### ISSUE TITLE
Add hotspot icon to mutation collapsible

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3694]
```[tasklist]
### Tasks
- [x] Create a new flag with hotspot version(v1)
- [x] Add alteration/flag association
- [x] add all hotspots into alteration table
- [x] In the curation page, make an API to find all relevant alterations for curated mutations
- [x] Show hotspot icon when the relevant alteration is hotspot
```
