### ISSUE TITLE
Allow user to add alias for string mutations

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3701]
### Requests
- Address overriding the default string mutation name with a custom term for the string mutation.
   - Request: `Would it be possible to be able to rename a string (like how we use brackets on the current system)? Right now in the platform we sometimes need to rename a string of mutations so that on the actionable genes table the biomarker isnt just a list of random mutations. Ex “ESR1 D538, E380, Y537, L536, L469V, S463P” = “ESR1 Oncogenic ligand-binding domain missense mutations”. While the current platform has the ability to rename a single mutation it doesnt have the ability to rename a string of mutations`
- Allow user to add a comment for entire string mutation. Currently, we can only add comments on each individual alteration
   - Request: `Could it be possible not only to rename a string (see above) but also to leave a hidden note for oursolves about what a string is? (equivalent to how we currently use parenthesis) eg “D538, E380, Y537 (nilotinib sensitive melanoma)”` - needs to be confirmed by @calvinlu3 

```[tasklist]
### Tasks
- [x] Add a `Flags` CreatableSelect field that supports free text string. This will be used to rename/categorize string mutations
- [x] Save the `Flags` in Mutation Firebase model and trigger API call to save flag(s) to database. The flag `name` should - convert special characters to space -> merge consecutive spaces -> replace space with underscore to generate the`flag` field. `type` field should be `ALTERATION`
- [x] Add a `Comment` field for string mutations
- [x] Once mutation string flags and comment are saved, the information will appear as a badge next to the mutation title.
- [x] Move the NoEntryBadge to the right
- [x] In mutation title - Convert alteration comments to an info icon (or comments bubble icon to keep consistency). The alteration name will stay in [sqaure brackets].
```
