### ISSUE TITLE
Support three letter AA

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3721]
We currently only support protein short(one letter code). It's not that difficult to support three letters but we have to be comprehensive. The following services need to all support it.

- 20 Amino Acids https://www.cryst.bbk.ac.uk/education/AminoAcid/the_twenty.html

```[tasklist]
### Tasks
- [ ] https://github.com/oncokb/oncokb/issues/3754
- [ ] https://github.com/oncokb/oncokb/issues/3755
- [ ] https://github.com/oncokb/oncokb-pipeline/issues/446
```
