### ISSUE TITLE
User should be able to enable their account after its expired

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3785]
We send user an account renewal email 14, 3 days before the expiration. If the user fails to renew their account, their token is expired. Their account is still activated though.

Now if the user tries to login again, we do provide a message with  `Your account has expired`, but without any ability to reenable it besides sending us an email.

```[tasklist]
### Tasks
- [ ] In the interface where the user sees `Your account has expired`, we should explain the reason it's expired is because they failed to verify the ownership of the email.
- [ ] We will provide a button `Verify Your Email Now`
- [ ] The click event will trigger an email to be sent to the user email box with an verification url. 
- [ ] I don't think we have an email for the purpose above, but you can use the similar one verifyEmailBeforeAccountExpires.html (We don't use html version of the email, but the txt version)
```

**Comment by jfkonecn** [comment]
@zhx828 
I did some quick testing and it seems like we do provide a button to send an email again.

![image](https://github.com/user-attachments/assets/a50b380e-1836-40cb-984a-a51cf68fffd7)



In order to test this I did the following:

1. Added this snippet of code to the [`UserUUIDController.authorize` method](https://github.com/oncokb/oncokb-public/blob/master/src/main/java/org/mskcc/cbio/oncokb/web/rest/UserUUIDController.java#L63-L67).

```java
@PostMapping("/authenticate")
public ResponseEntity<UUID> authorize(@Valid @RequestBody LoginVM loginVM) {
    Boolean temp = true;
    if (temp) {
         throw new TokenExpiredException();
    }
   ...
}
```

3. Tried to log into my account.

**Comment by zhx828** [comment]
Next step: For HZ, we need to go back to user email to see how to reproduce the issue.
