### ISSUE TITLE
Ensembl versioning

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb#3827]
### Tasks
- [ ] Setup a local VEP on a static Ensembl version
- [x] Ensure GN Mongo cache only contains annotations from a single Ensembl version
- [x] Allow oncokb endpoint to take in an `ensembl_version` parameter (Not planned)

**Comment by bprize15** [comment]
- Add `/info/software` to local VEP to mimic Ensembl API
- Genome Nexus `/version` will hit `/info/software` to populate VEP version
- Speak to Avery about consolidating "cache" and "server" versions into one
- Speak to Avery about the following options for populating "static" flag
    - Delete "static"
    - Return "static" from VEP
    - Move "static" to `application.properties`
