### ISSUE TITLE
support pathway information in oncokb

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb#852]
This is not urgent.

We need to be able to curate pathway information in oncokb. For this round, we are only interested in whether a gene belongs to a pathway.

- [ ] we need a list of pathways and their genes. Maybe we can use the TCGA ones. @schultzn 
- [ ] on gene curation interface, add a multi-selection box to select the pathways a gene belongs to.
- [ ] make database change to add the pathway associations
- [ ] add associated pathway to the gene API endpoint
- [ ] add an endpoint to return genes of a pathway

In the clinical trial curation platform:
- [ ] In the hugoSymbol section, it should be changed to `hugo_symbol/pathway`. Once toggles to pathway, pull list of pathways from oncokb
- [ ] Automatically add `Oncogenic Mutations` once the pathway is added
- [ ] Annotation the pathway in realtime by using oncokb service (@victoria34  we need to discuss the details how this can be done)
